markdown: kramdown
highlighter: rouge
# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

permalink: /:categories/:title.html
name: teckoo.com
title: teckoo.com
exclude: ['doc']
